### ISSUE TITLE
Some website and youtube pages are not available

### ISSUE THREAD

**Issue by VahidR** [farhanashrafdev/90DaysOfCyberSecurity#2]
Hi, 

Great job indeed. 
There are some pages, however, that does not work anymore and need an update. 
Some of them are: 

> Take the Wireshark University course: https://wireshark.org/training/
> Follow the Wireshark Tutorial on guru99: https://guru99.com/wireshark-tutorial.html
> Watch the Suricata IDS/IPS System Tutorial on YouTube: https://youtube.com/watch?v=DZl7mW8OvZg
> Read through the Suricata on pfSense guide: https://doc.pfsense.org/index.php/Suricata

**Comment by farhanashrafdev** [comment]
Hey @VahidR thank you for highlighting, let me update the repository once again.

**Comment by farhanashrafdev** [comment]
@VahidR Repository is updated :)

**Comment by VahidR** [comment]
Much appreciated...
