### ISSUE TITLE
List of unavailable links

### ISSUE THREAD

**Issue by Sythsaz** [farhanashrafdev/90DaysOfCyberSecurity#5]
<details><summary>Broken Links</summary>

### Day 29-42: Python
 - Follow SoloLearn's Python Tutorial: https://sololearn.com/Course/Python/

### Day 43-56: Traffic Analysis
 - Take the Wireshark University course: https://wireshark.org/training/
 - Follow the Wireshark Tutorial on guru99: https://guru99.com/wireshark-tutorial.html
 - Watch the Suricata IDS/IPS System Tutorial on YouTube: https://youtube.com/watch?v=DZl7mW8OvZg
 - Read through the Suricata on pfSense guide: https://doc.pfsense.org/index.php/Suricata

### Day 64-70: ELK
 - Follow the ELK Stack Tutorial on Logz.io: https://logz.io/learn/complete-elk-stack-tutorial/
 - Browse through the ELK Stack tutorials on Elastic: https://elastic.co/learn/elastic-stack

### Day 85-90: Hacking
 - Practice on Cyber Talents: https://cybertalents/

### Day 91-92: One Page Resume
 - Cybersecurity Resume Template from Hiration: https://www.hiration.com/resume-templates/cybersecurity-resume-template/ This template is specifically designed for cybersecurity professionals and includes sections for skills, certifications, and professional experience, along with a summary and a skills section.
 - Cybersecurity Resume from MyPerfectResume: https://www.myperfectresume.com/resume-templates/cybersecurity This template is also designed for cybersecurity professionals and includes sections for skills, certifications, and experience, along with a summary, and a section for education.
 - Cybersecurity Resume from Resume-Now: https://www.resume-now.com/templates/cyber-security-resume This template also has sections for skills, certifications, and experience, along with a summary, and a section for education. It also includes a section for technical skills.

</details> 

<details><summary> A paid subscription?</summary>

### Day 78-84: Azure
 - Read the Introduction to Microsoft Azure: https://bowtiedcyber.substack.com/p/introduction-to-microsoft-azure

</details> 

Thank you for all your work!

**Comment by seharbat00l** [comment]
Is this issue fixed?

**Comment by farhanashrafdev** [comment]
> Is this issue fixed?

Not yet

**Comment by seharbat00l** [comment]
I can try to fix it. You can assign this to me.

**Comment by farhanashrafdev** [comment]
@Sythsaz thanks for highlighting I have just updated these links :)

**Comment by farhanashrafdev** [comment]
@seharbat00l you can review the path, and suggest changes. or add resources which you found useful. 
You can contribute to repository this way.

**Comment by seharbat00l** [comment]
Sure !
